import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { scrapePage } from "@/lib/ingest.server";
import { parseRoster, cardLines } from "@/lib/roster-extract";
const cl = parseRoster(readFileSync("/tmp/d2/clemson-sb.md","utf8"), "softball");
for (const p of cl.players) if (/harrington|maness|clopton|burmeister/i.test(p.name)) console.log("CLEM", p.name, p.class_year, p.class_year_raw, p.position, p.hometown);
const url = execFileSync("psql",["-At","-c",`select pr.roster_url from programs pr join universities u on u.id=pr.university_id where u.name like 'Tompkins%' and pr.sport='baseball'`],{encoding:"utf8"}).trim();
const page:any = await scrapePage(url);
const md = page.markdown ?? page.content ?? "";
const lines = cardLines(md.split("\n").map(l=>l.replace(/\s+/g," ").trim()).filter(Boolean));
const at = lines.findIndex(l=>l.includes("Barbeau"));
console.log(JSON.stringify(lines.slice(at-2, at+8), null, 1));
