import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { scrapePage } from "@/lib/ingest.server";
import { parseRoster } from "@/lib/roster-extract";
const url = execFileSync("psql",["-At","-c",`select pr.roster_url from programs pr join universities u on u.id=pr.university_id where u.name='Clemson University' and pr.sport='softball'`],{encoding:"utf8"}).trim();
const page:any = await scrapePage(url);
const md = page.markdown ?? page.content ?? "";
writeFileSync("/tmp/d2/clemson-sb.md", md);
const s = parseRoster(md, "softball");
console.log(JSON.stringify(s.counts));
console.log(JSON.stringify(s.players.slice(0,3)));
