/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCompareRouteImport } from './routes/_authenticated/compare'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFamilyRouteImport } from './routes/_authenticated/family'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminMajorsRouteImport } from './routes/_authenticated/admin.majors'
import { Route as AuthenticatedProgramsIdRouteImport } from './routes/_authenticated/programs.$id'
import { Route as AuthenticatedRosterIndexRouteImport } from './routes/_authenticated/roster.index'
import { Route as AuthenticatedRosterNewRouteImport } from './routes/_authenticated/roster.new'
import { Route as AuthenticatedAdminProgramsIndexRouteImport } from './routes/_authenticated/admin.programs.index'
import { Route as AuthenticatedAdminProgramsIdRouteImport } from './routes/_authenticated/admin.programs.$id'
import { Route as AuthenticatedAdminProgramsNewRouteImport } from './routes/_authenticated/admin.programs.new'
import { Route as AuthenticatedAdminSchoolsNewRouteImport } from './routes/_authenticated/admin.schools.new'
import { Route as AuthenticatedAdminUniversitiesIndexRouteImport } from './routes/_authenticated/admin.universities.index'
import { Route as AuthenticatedAdminUniversitiesIdRouteImport } from './routes/_authenticated/admin.universities.$id'
import { Route as AuthenticatedAdminProgramsIdEditRouteImport } from './routes/_authenticated/admin.programs.$id_.edit'
import { Route as AuthenticatedAdminUniversitiesIdEditRouteImport } from './routes/_authenticated/admin.universities.$id_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompareRoute = AuthenticatedCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilyRoute = AuthenticatedFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMajorsRoute =
  AuthenticatedAdminMajorsRouteImport.update({
    id: '/majors',
    path: '/majors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedProgramsIdRoute = AuthenticatedProgramsIdRouteImport.update({
  id: '/programs/$id',
  path: '/programs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRosterIndexRoute =
  AuthenticatedRosterIndexRouteImport.update({
    id: '/roster/',
    path: '/roster/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRosterNewRoute = AuthenticatedRosterNewRouteImport.update({
  id: '/roster/new',
  path: '/roster/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminProgramsIndexRoute =
  AuthenticatedAdminProgramsIndexRouteImport.update({
    id: '/programs/',
    path: '/programs/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProgramsIdRoute =
  AuthenticatedAdminProgramsIdRouteImport.update({
    id: '/programs/$id',
    path: '/programs/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProgramsNewRoute =
  AuthenticatedAdminProgramsNewRouteImport.update({
    id: '/programs/new',
    path: '/programs/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSchoolsNewRoute =
  AuthenticatedAdminSchoolsNewRouteImport.update({
    id: '/schools/new',
    path: '/schools/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUniversitiesIndexRoute =
  AuthenticatedAdminUniversitiesIndexRouteImport.update({
    id: '/universities/',
    path: '/universities/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUniversitiesIdRoute =
  AuthenticatedAdminUniversitiesIdRouteImport.update({
    id: '/universities/$id',
    path: '/universities/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProgramsIdEditRoute =
  AuthenticatedAdminProgramsIdEditRouteImport.update({
    id: '/programs/$id_/edit',
    path: '/programs/$id/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUniversitiesIdEditRoute =
  AuthenticatedAdminUniversitiesIdEditRouteImport.update({
    id: '/universities/$id_/edit',
    path: '/universities/$id/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/compare': typeof AuthenticatedCompareRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/search': typeof AuthenticatedSearchRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/majors': typeof AuthenticatedAdminMajorsRoute
  '/programs/$id': typeof AuthenticatedProgramsIdRoute
  '/roster/new': typeof AuthenticatedRosterNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/roster/': typeof AuthenticatedRosterIndexRoute
  '/admin/programs/$id': typeof AuthenticatedAdminProgramsIdRoute
  '/admin/programs/new': typeof AuthenticatedAdminProgramsNewRoute
  '/admin/schools/new': typeof AuthenticatedAdminSchoolsNewRoute
  '/admin/universities/$id': typeof AuthenticatedAdminUniversitiesIdRoute
  '/admin/programs/': typeof AuthenticatedAdminProgramsIndexRoute
  '/admin/universities/': typeof AuthenticatedAdminUniversitiesIndexRoute
  '/admin/programs/$id/edit': typeof AuthenticatedAdminProgramsIdEditRoute
  '/admin/universities/$id/edit': typeof AuthenticatedAdminUniversitiesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/search': typeof AuthenticatedSearchRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/majors': typeof AuthenticatedAdminMajorsRoute
  '/programs/$id': typeof AuthenticatedProgramsIdRoute
  '/roster/new': typeof AuthenticatedRosterNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/roster': typeof AuthenticatedRosterIndexRoute
  '/admin/programs/$id': typeof AuthenticatedAdminProgramsIdRoute
  '/admin/programs/new': typeof AuthenticatedAdminProgramsNewRoute
  '/admin/schools/new': typeof AuthenticatedAdminSchoolsNewRoute
  '/admin/universities/$id': typeof AuthenticatedAdminUniversitiesIdRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsIndexRoute
  '/admin/universities': typeof AuthenticatedAdminUniversitiesIndexRoute
  '/admin/programs/$id/edit': typeof AuthenticatedAdminProgramsIdEditRoute
  '/admin/universities/$id/edit': typeof AuthenticatedAdminUniversitiesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/compare': typeof AuthenticatedCompareRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/family': typeof AuthenticatedFamilyRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/majors': typeof AuthenticatedAdminMajorsRoute
  '/_authenticated/programs/$id': typeof AuthenticatedProgramsIdRoute
  '/_authenticated/roster/new': typeof AuthenticatedRosterNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/roster/': typeof AuthenticatedRosterIndexRoute
  '/_authenticated/admin/programs/$id': typeof AuthenticatedAdminProgramsIdRoute
  '/_authenticated/admin/programs/new': typeof AuthenticatedAdminProgramsNewRoute
  '/_authenticated/admin/schools/new': typeof AuthenticatedAdminSchoolsNewRoute
  '/_authenticated/admin/universities/$id': typeof AuthenticatedAdminUniversitiesIdRoute
  '/_authenticated/admin/programs/': typeof AuthenticatedAdminProgramsIndexRoute
  '/_authenticated/admin/universities/': typeof AuthenticatedAdminUniversitiesIndexRoute
  '/_authenticated/admin/programs/$id_/edit': typeof AuthenticatedAdminProgramsIdEditRoute
  '/_authenticated/admin/universities/$id_/edit': typeof AuthenticatedAdminUniversitiesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/admin'
    | '/compare'
    | '/dashboard'
    | '/family'
    | '/search'
    | '/admin/audit'
    | '/admin/majors'
    | '/programs/$id'
    | '/roster/new'
    | '/admin/'
    | '/roster/'
    | '/admin/programs/$id'
    | '/admin/programs/new'
    | '/admin/schools/new'
    | '/admin/universities/$id'
    | '/admin/programs/'
    | '/admin/universities/'
    | '/admin/programs/$id/edit'
    | '/admin/universities/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/compare'
    | '/dashboard'
    | '/family'
    | '/search'
    | '/admin/audit'
    | '/admin/majors'
    | '/programs/$id'
    | '/roster/new'
    | '/admin'
    | '/roster'
    | '/admin/programs/$id'
    | '/admin/programs/new'
    | '/admin/schools/new'
    | '/admin/universities/$id'
    | '/admin/programs'
    | '/admin/universities'
    | '/admin/programs/$id/edit'
    | '/admin/universities/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/compare'
    | '/_authenticated/dashboard'
    | '/_authenticated/family'
    | '/_authenticated/search'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/majors'
    | '/_authenticated/programs/$id'
    | '/_authenticated/roster/new'
    | '/_authenticated/admin/'
    | '/_authenticated/roster/'
    | '/_authenticated/admin/programs/$id'
    | '/_authenticated/admin/programs/new'
    | '/_authenticated/admin/schools/new'
    | '/_authenticated/admin/universities/$id'
    | '/_authenticated/admin/programs/'
    | '/_authenticated/admin/universities/'
    | '/_authenticated/admin/programs/$id_/edit'
    | '/_authenticated/admin/universities/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compare': {
      id: '/_authenticated/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AuthenticatedCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family': {
      id: '/_authenticated/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof AuthenticatedFamilyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/majors': {
      id: '/_authenticated/admin/majors'
      path: '/majors'
      fullPath: '/admin/majors'
      preLoaderRoute: typeof AuthenticatedAdminMajorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/programs/$id': {
      id: '/_authenticated/programs/$id'
      path: '/programs/$id'
      fullPath: '/programs/$id'
      preLoaderRoute: typeof AuthenticatedProgramsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster/': {
      id: '/_authenticated/roster/'
      path: '/roster'
      fullPath: '/roster/'
      preLoaderRoute: typeof AuthenticatedRosterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster/new': {
      id: '/_authenticated/roster/new'
      path: '/roster/new'
      fullPath: '/roster/new'
      preLoaderRoute: typeof AuthenticatedRosterNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/programs/': {
      id: '/_authenticated/admin/programs/'
      path: '/programs'
      fullPath: '/admin/programs/'
      preLoaderRoute: typeof AuthenticatedAdminProgramsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/programs/$id': {
      id: '/_authenticated/admin/programs/$id'
      path: '/programs/$id'
      fullPath: '/admin/programs/$id'
      preLoaderRoute: typeof AuthenticatedAdminProgramsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/programs/new': {
      id: '/_authenticated/admin/programs/new'
      path: '/programs/new'
      fullPath: '/admin/programs/new'
      preLoaderRoute: typeof AuthenticatedAdminProgramsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/schools/new': {
      id: '/_authenticated/admin/schools/new'
      path: '/schools/new'
      fullPath: '/admin/schools/new'
      preLoaderRoute: typeof AuthenticatedAdminSchoolsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/universities/': {
      id: '/_authenticated/admin/universities/'
      path: '/universities'
      fullPath: '/admin/universities/'
      preLoaderRoute: typeof AuthenticatedAdminUniversitiesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/universities/$id': {
      id: '/_authenticated/admin/universities/$id'
      path: '/universities/$id'
      fullPath: '/admin/universities/$id'
      preLoaderRoute: typeof AuthenticatedAdminUniversitiesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/programs/$id_/edit': {
      id: '/_authenticated/admin/programs/$id_/edit'
      path: '/programs/$id/edit'
      fullPath: '/admin/programs/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminProgramsIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/universities/$id_/edit': {
      id: '/_authenticated/admin/universities/$id_/edit'
      path: '/universities/$id/edit'
      fullPath: '/admin/universities/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminUniversitiesIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminMajorsRoute: typeof AuthenticatedAdminMajorsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminProgramsIdRoute: typeof AuthenticatedAdminProgramsIdRoute
  AuthenticatedAdminProgramsNewRoute: typeof AuthenticatedAdminProgramsNewRoute
  AuthenticatedAdminSchoolsNewRoute: typeof AuthenticatedAdminSchoolsNewRoute
  AuthenticatedAdminUniversitiesIdRoute: typeof AuthenticatedAdminUniversitiesIdRoute
  AuthenticatedAdminProgramsIndexRoute: typeof AuthenticatedAdminProgramsIndexRoute
  AuthenticatedAdminUniversitiesIndexRoute: typeof AuthenticatedAdminUniversitiesIndexRoute
  AuthenticatedAdminProgramsIdEditRoute: typeof AuthenticatedAdminProgramsIdEditRoute
  AuthenticatedAdminUniversitiesIdEditRoute: typeof AuthenticatedAdminUniversitiesIdEditRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminMajorsRoute: AuthenticatedAdminMajorsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminProgramsIdRoute: AuthenticatedAdminProgramsIdRoute,
  AuthenticatedAdminProgramsNewRoute: AuthenticatedAdminProgramsNewRoute,
  AuthenticatedAdminSchoolsNewRoute: AuthenticatedAdminSchoolsNewRoute,
  AuthenticatedAdminUniversitiesIdRoute: AuthenticatedAdminUniversitiesIdRoute,
  AuthenticatedAdminProgramsIndexRoute: AuthenticatedAdminProgramsIndexRoute,
  AuthenticatedAdminUniversitiesIndexRoute:
    AuthenticatedAdminUniversitiesIndexRoute,
  AuthenticatedAdminProgramsIdEditRoute: AuthenticatedAdminProgramsIdEditRoute,
  AuthenticatedAdminUniversitiesIdEditRoute:
    AuthenticatedAdminUniversitiesIdEditRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCompareRoute: typeof AuthenticatedCompareRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFamilyRoute: typeof AuthenticatedFamilyRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedProgramsIdRoute: typeof AuthenticatedProgramsIdRoute
  AuthenticatedRosterNewRoute: typeof AuthenticatedRosterNewRoute
  AuthenticatedRosterIndexRoute: typeof AuthenticatedRosterIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCompareRoute: AuthenticatedCompareRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFamilyRoute: AuthenticatedFamilyRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedProgramsIdRoute: AuthenticatedProgramsIdRoute,
  AuthenticatedRosterNewRoute: AuthenticatedRosterNewRoute,
  AuthenticatedRosterIndexRoute: AuthenticatedRosterIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
